[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Add this line to enable --via-ir
via_ir = true

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "solidity-examples/=lib/solidity-examples/",
]

# Optimizer settings
optimizer = true
optimizer_runs = 200

# EVM version
evm_version = "paris"

# Solc version - update this to match your requirements
solc_version = "0.8.27"



# Additional settings
fuzz_runs = 1000
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "${MainnetAlchemyAPI}"
tenderlyMainnet = "${TenderlyMainnetRPC}"
sepolia = "${SepoliaRPC}"
[etherscan]
mainnet = { key = "${EtherscanApiKey}" }
sepolia = { key = "${EtherscanApiKey}" }
